spring:
  datasource:
    url: jdbc:h2:mem:quotesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  flyway:
    enabled: true
    locations: classpath:db/migration
  mvc:
    log-resolved-exception: true
    problemdetails:
      enabled: true
    apiversion:
      use:
        header: API-Version
      required: false
logging:
  level:
    org.flywaydb.core: info
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler: debug
  pattern:
    console: '%-5level %clr(%c{0}){cyan} : %m%n'