spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:50829/quotes
    username: quotes
    password: quotes
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
