spring:
  datasource:
    url: jdbc:h2:mem:quotesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb.core: info
